export const ADD_TO_CART = 'ADD_TO_CART'
export const CHANGE_PRODUCT_QUANTITY = 'CHANGE_PRODUCT_QUANTITY'
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART'
export const RESET_SHOPPING_CART = 'RESET_SHOPPING_CART'
